project:
  type: book
  output-dir: docs
  # output-file: docs
  # output-dir: pdf_doc
  # output-file: pdf_doc
  # 
book:
  title: "IAB R Crash Course 2025"
  author: "Andreas Filser"
  date: last-modified
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_intro.qmd
    - 03_desc.qmd
    - 04_data_wrangle.qmd
    - 07_viz_translated.qmd
    - 09_reg.qmd
    - 09_reg2.qmd
    - 10_raw_to_table.qmd
    - 05_merge_pivot.qmd
    - 06_labels_factor.qmd
    - 15_map.qmd
    # - 14_tabellenexport.qmd
    # - 07_inferenz.qmd
    # - 10_log_reg.qmd
    # - 12_apply_loop.qmd
    # - 15_RMarkdown.qmd
    # - 17_errors.qmd
    - references_translated.qmd
  language: de-DE
  # downloads: [pdf]
  page-footer:
   center: |
      All content {{< fa brands creative-commons >}} 2024 by [Andreas Filser](https://afilser.netlify.app/)<br>
      [CC Lizenz mit Namensnennung {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}](https://creativecommons.org/licenses/by-nc/4.0/)<br>
      Created using {{< fa brands r-project >}}, Code [can be viewed here {{< fa brands github >}}](https://github.com/filius23/GradAB_R2024)
      
      
callout-appearance: simple

bibliography: references.bib

format:
  html:
    theme: flatly
    page-layout: full
    css: style.css
  # pdf:
  #   documentclass: scrreprt # kapitel02 kable

execute:
  freeze: auto
  cache: true
from: markdown+emoji
mainfont: Red Hat Display